### ISSUE TITLE
Ownership and Contributions

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Centril/rust-safe#1]
Are there any plans to add code to this crate? I've done a fair amount of FFI work in Rust and am currently wanting to review a crate (see [discussion](https://users.rust-lang.org/t/is-there-a-checklist-for-review-of-unsafe-code/28414/17)/[repo](https://github.com/Michael-F-Bryan/libsignal-protocol-rs)), preferably using some sort of `#[safe]` attribute.

I'd be happy to do the work implementing the attribute macro. Otherwise I could take on the job of maintaining the crate.

**Comment by TimDiekmann** [comment]
@Michael-F-Bryan not answering your question, but I think [safety-guard](https://crates.io/crates/safety-guard) could be interesting for you anyway (Disclaimer: I'm the author of the crate).

> Adds a `#[safety]` attribute for functions. The attribute adds a `# Safety section` to the documentation of the function and tests the given constraints in debug builds.

I know that `#[safe]` is for `unsafe {}` blocks, not for functions, but it's kind of related.

**Comment by Michael-F-Bryan** [comment]
Thanks for the link @TimDiekmann! In my case, I'm trying to write a safe abstraction over unsafe code, so ideally the public API will have zero `unsafe` functions, but that could come in handy for documenting our internals.

**Comment by Centril** [comment]
@Michael-F-Bryan Hey :) Unfortunately I haven't had the time to implement anything here... language team duties and all keep me busy. I would be happy to collaborate with you and review some code. If you want to be a lead/co-maintainer I would be happy for that as well.

@TimDiekmann You are welcome to join also. :)

**Comment by Centril** [comment]
I think we can close this now that this is resolved. :)
